# Dockerfile.frontend
#

FROM node:24.4-slim

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

CMD ["sh", "-c", "if [ \"$UPDATE_DEPS\" = \"true\" ]; then npm update && npm run build; fi; npm run preview"]
