# Dockerfile.frontend

FROM node:20

WORKDIR /app

# Copy only package files first (cache layer)
COPY package*.json ./

# Install dependencies inside the image
RUN npm install

# Now copy the rest of your source code
COPY . .

# Default command (for dev)
CMD ["npm", "run", "dev"]
