# Dockerfile.frontend

FROM node:20-alpine

WORKDIR /app

# Copy only package files first (cache layer)
COPY package*.json ./

# Install dependencies inside the image
RUN npm install

RUN npm run build

# Now copy the rest of your source code
COPY . .

EXPOSE 3000
CMD ["npm", "run", "preview"]
