version: "3.9"
services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    environment:
      - INTERNAL_SECRET=s3cr3t-long-random
    depends_on:
      - backend
    networks: [appnet]

  backend:
    build: ./backend
    environment:
      - INTERNAL_SECRET=s3cr3t-long-random
      - NODE_ENV=production
      - UI_ORIGIN=http://localhost
    networks: [appnet]

networks:
  appnet:
    driver: bridge
