# docker-compose.yml
services:
  proxy:
    image: nginx:alpine
    ports:
      - "8080:8080"
    environment:
      INTERNAL_SECRET: ${INTERNAL_SECRET}
      # tell nginx where the template is and where to write the rendered config
      NGINX_ENVSUBST_TEMPLATE_DIR: /etc/nginx/templates
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      NGINX_ENVSUBST_VARS: '$INTERNAL_SECRET'
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./backend/certs:/etc/nginx/certs:ro
    depends_on:
      - conference-backend
      - conference-ui
    networks: [appnet]

  conference-ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    networks: [ appnet ]

  conference-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    environment:
      UPDATE_DEPS: ${UPDATE_DEPS:-false}
    depends_on:
      - conference-db
    networks: [appnet]

  conference-db:
    image: mariadb:10.11
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks: [appnet]

networks:
  appnet:
    driver: bridge

volumes:
  mariadb_data:
