# docker-compose.yml

services:

  conference-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    image: conference-reg-app:dev
    ports:
      - "8080:3000"
    labels:
      - "com.project.name=conference-frontend"
      - "com.project.description=React app for conference registration"
    depends_on:
      - conference-backend

  conference-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    image: conference-reg-ws:dev
    ports:
      - "5001:5000"
    env_file:
      - .env
    labels:
      - "com.project.name=conference-backend"
      - "com.project.description=Express API for conference registration"
    depends_on:
      - conference-db
    volumes:
      - ./backend:/app

  conference-db:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    labels:
      - "com.project.name=conference-db"
      - "com.project.description=MariaDB instance for attendee data"

  drizzle-runner:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    env_file:
      - .env
    working_dir: /app/backend
    entrypoint: node
    depends_on:
      - conference-db

volumes:
  mariadb_data:
