# docker-compose.yml (dev profile)
services:
  conference-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    image: conference-reg-app:dev
    container_name: conference_ui
    restart: unless-stopped
    working_dir: /app/frontend
    environment:
      NODE_ENV: development
    ports:
      - "127.0.0.1:8080:3000"
    volumes:
      - ./frontend:/app/frontend
      - ./backend/certs:/certs:ro
    command: npm run dev
    depends_on:
      - conference-backend
    profiles: ["dev"]

  conference-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    image: conference-reg-ws:dev
    container_name: conference_ws
    restart: unless-stopped
    working_dir: /app/backend
    env_file:
      - .env
    environment:
      NODE_ENV: development
      BIND_HOST: 0.0.0.0
      BACKEND_PORT: 5000
      HTTPS: "true"
      HTTPS_CERT: /certs/localhost.pem
      HTTPS_KEY:  /certs/localhost-key.pem
      LOG_DIR: /var/log/conference
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_TO_FILE: ${LOG_TO_FILE:-true}
      CHOKIDAR_USEPOLLING: "1"
      CHOKIDAR_INTERVAL: "200"
    ports:
      - "127.0.0.1:5443:5000"
      # API at https://127.0.0.1:5443
    volumes:
      - ./backend:/app/backend
      - ./backend/certs:/certs:ro
      - conference_logs:/var/log/conference
    command: >
      sh -c "
        npm ci &&
        npm run dev
      "
    depends_on:
      conference-db:
        condition: service_healthy
    profiles: ["dev"]

  conference-db:
    image: mariadb:10.11
    container_name: conference_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      # use CMD-SHELL so ${…} expands
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u${DB_USER} -p${DB_PASSWORD} --silent"]
      interval: 3s
      timeout: 3s
      retries: 20
    profiles: ["dev"]

volumes:
  mariadb_data:
  conference_logs:
