# docker-compose.yml

services:

  conference-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    image: conference-reg-app:dev
    container_name: conference_ui
    restart: unless-stopped
    ports:
      - "8080:3000"
    labels:
      - "com.project.name=conference-frontend"
      - "com.project.description=React app for conference registration"
    depends_on:
      - conference-backend

  conference-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    image: conference-reg-ws:dev
    container_name: conference_ws
    restart: unless-stopped
    ports:
      - "5001:5000"
    env_file:
      - .env
    labels:
      - "com.project.name=conference-backend"
      - "com.project.description=Express API for conference registration"
    depends_on:
      - conference-db

  conference-db:
    image: mariadb:10.11
    container_name: conference_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    labels:
      - "com.project.name=conference-db"
      - "com.project.description=MariaDB instance for attendee data"

  drizzle-runner:
    profiles: ["studio"]
    container_name: drizzle_studio
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    working_dir: /app/backend
    volumes:
      - ./:/app:delegated
      - drizzle_runner_node_modules:/app/backend/node_modules
      - drizzle_runner_migrations:/app/backend/drizzle/migrations
      - ./certs/local.drizzle.studio.pem:/app/backend/local.drizzle.studio.pem:ro
      - ./certs/local.drizzle.studio-key.pem:/app/backend/local.drizzle.studio-key.pem:ro
    env_file:
      - .env
    ports:
      - "3337:3337"   # UI
      - "4983:4983"   # RPC
    entrypoint: ["sh","-c"]
    depends_on:
      - conference-db

volumes:
  mariadb_data:
  drizzle_runner_node_modules:
  drizzle_runner_migrations:
